Raster Query Fields
wri/gfw-data-api pull request #166
Opened 2021-03-31 19:40 UTC by jterry64

Eventually, we want the /fields endpoint on raster tile set to list all the fields available for raster OTF queries by drawing from the raster tile sets in the API. 

However, I won't have time to work on this for awhile, so I wanted to just temporarily create the fields endpoint using hardcoded fields so users at least have some documentation on the available fields.

2021-03-31 20:48 UTC, dmannarino approved these changes

2021-04-06 15:01 UTC, thomas-maschler requested changes

2021-04-07 15:55 UTC, jterry64 commented on app/models/enum/analysis.py
> +    },
what do you mean? as in remove it from the field_name_ and only include it in the field_type?

2021-04-23 18:17 UTC, jterry64 commented
I think we can wait until I just finish the full solution now, so closing this PR

2021-04-23 18:17 UTC, closed without merging