Hotfix OTF issues with case sensitivity
wri/gfw-data-api pull request #217
Opened 2021-07-06 16:11 UTC by jterry64

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [X] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [X] Check the commit's or even all commits' message styles matches our requested structure.
- [X] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
SQL string is always lower cased, which breaks layer names with uppercase values (e.g. "Mg")
/analysis/zonal endpoint isn't using updated values for boolean layers

Issue Number: N/A

## What is the new behavior? 

- Don't lowercase SQL string
- Use 'false' instead of 0 for boolean layers

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

2021-07-06 16:38 UTC, dmannarino submitted a review, later dismissed

2021-07-06 16:40 UTC, thomas-maschler requested changes
Tests please!
In particular for Hotfixes

2021-07-06 16:46 UTC, jterry64 commented
> Tests please!
> In particular for Hotfixes

@dmannarino at some point you set the OTF tests to skip with the detail "Moto not up to the task... Need localstack to test". Is this still the case?

2021-07-07 18:01 UTC, jterry64 commented
@thomas-maschler added a test for a raster queries

2021-07-07 18:22 UTC, thomas-maschler approved these changes

2021-07-08 14:30 UTC, merged