Gtc 3081 geoencoder endpoint
wri/gfw-data-api pull request #616
Opened 2024-12-23 19:24 UTC by dmannarino

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [ ] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-12-31 21:54 UTC, danscales reviewed
Looks great!  Just a few minor comments

2024-12-31 21:55 UTC, danscales commented
> Looks great! Just a few minor comments

And great job with the tests!

2025-01-02 19:34 UTC, jterry64 requested changes
Loving all the unit tests, had a few comments on style and documentation. Also, would possibly be able to update the PR with examples of requests/responses like Gary was doing for his GADM PRs? I found that quite helpful for assessing if the PR is actually doing what you're intending

2025-01-02 19:34 UTC, jterry64 commented on app/routes/thematic/geoencoder.py
> +        "GADM", description="The source of administrative boundaries to use."
Should we document that right now the only option is "GADM"?

2025-01-02 19:34 UTC, jterry64 commented on app/routes/thematic/geoencoder.py
> +        description="Version of the administrative boundaries dataset to use.",
Similar, is there a way to document the choices available? I guess this may get more confusing if ever have multiple providers

2025-01-02 19:34 UTC, jterry64 commented on app/routes/thematic/geoencoder.py
> +    await version_is_valid(dataset, version_str)
Like mentioned about the documentation above, should it be well known in advance which versions we support for providers, rather than just trying and throwing back an error?

2025-01-02 19:34 UTC, jterry64 commented on app/routes/thematic/geoencoder.py
> +        data={
This might be cleaner as a pydantic model instead of a dict

2025-01-02 19:34 UTC, jterry64 commented on app/routes/thematic/geoencoder.py
> +                        "id": match["gid_0"].rsplit("_")[0],
A function for getting the ID here would be easier to read

2025-01-02 19:34 UTC, jterry64 commented on app/routes/thematic/geoencoder.py
> +                            if adm_level >= 1
nitpick, I personally find ternary operators declared inside dicts confusing to read

2025-01-02 19:34 UTC, jterry64 commented on app/routes/thematic/geoencoder.py
> +                for match in json_data
same with nested list comprehensions as above

2025-01-02 19:34 UTC, jterry64 commented on app/routes/thematic/geoencoder.py
> +    if re.match(VERSION_REGEX, version) is None:
per above, maybe just have pre-validated versions rather than checking the version

2025-01-02 23:22 UTC, jterry64 commented on app/routes/thematic/geoencoder.py
> +        description="Version of the administrative boundaries dataset to use.",
Wild idea: should we consolidate admin version and admin dataset to one field, and have the options be like: "GADM 3.6", "GADM 4.1", "geoBoundaries 1.0", "middleEarth 3.2". Then it'll be clear what you're getting from a set of options.

2025-01-08 21:05 UTC, gtempus commented on app/routes/thematic/geoencoder.py
> +        description="Version of the administrative boundaries dataset to use.",
Combining the provider and version has merit (`middleEarth 3.2`). It has excellent cohesion.
This is such a simple scenario that it's hard to justify breaking it up.

However, we'd be encoding a string with special information (i.e., _provider_`space`_version_).
It's generally a good practice to split information up even though it makes for a bit more complexity.
It's more flexible in the long run (although I'm starting to violate YAGNI with this statement).
Finally, we are splitting this information up in the area/geostore microservice interface for all of the reasons mentioned above. 

That's my two cents.

2025-01-08 21:19 UTC, jterry64 commented on app/routes/thematic/geoencoder.py
> +import re
@dmannarino I know you said you didn't like thematic. I was thinking of other ideas, is this admin area specific endpoints, maybe we just put it under like something like "political"? E.g. `/political/geoencoder`. Then the future can include additional GADM endpoints, WDPA, concessions, etc. Not sure if we need to distinguish it from the rest of the API, or we can just have it all in under a header in the docs.

2025-01-08 21:21 UTC, jterry64 commented on app/routes/thematic/geoencoder.py
> +import re
But I do think `geoencoder` is a little vague if it only works for admin areas, geoencoding implies converting any text of the place into coordinates: https://en.wikipedia.org/wiki/Address_geocoding

2025-01-21 19:27 UTC, dmannarino commented on app/routes/thematic/geoencoder.py
> +    names = []
Done, thanks!

2025-01-21 19:27 UTC, dmannarino commented on app/routes/thematic/geoencoder.py
> +        description="Whether or not to perform a case- and accent-insensitive search.",
Think I need to even with the `default` argument set to True?

2025-01-21 19:28 UTC, dmannarino commented
> > Looks great! Just a few minor comments
> 
> And great job with the tests!

Thanks!

2025-01-21 20:40 UTC, danscales commented on app/routes/thematic/geoencoder.py
> +        description="Whether or not to perform a case- and accent-insensitive search.",
OK, no, no change needed, I see now that the Default value (if not None) is displayed in the documentation.

2025-01-24 03:21 UTC, dmannarino commented on app/routes/thematic/geoencoder.py
> +        "GADM", description="The source of administrative boundaries to use."
Done!

2025-01-24 03:25 UTC, dmannarino commented on app/routes/thematic/geoencoder.py
> +    await version_is_valid(dataset, version_str)
I fundamentally agree that your suggestion is a good one, but it turns out to be difficult to do in practice. Especially considering the limited use of this endpoint and the fact that we will be omitting it from the docs.

2025-01-25 21:25 UTC, dmannarino commented on app/routes/thematic/geoencoder.py
> +import re
Changed to /political/id-lookup

2025-01-27 15:37 UTC, dmannarino commented on app/routes/thematic/geoencoder.py
> +                        "id": match["gid_0"].rsplit("_")[0],
Done!

2025-01-27 15:37 UTC, dmannarino commented on app/routes/thematic/geoencoder.py
> +                            if adm_level >= 1
I think they're all gone!

2025-01-27 15:38 UTC, dmannarino commented on app/routes/thematic/geoencoder.py
> +                for match in json_data
Banished!

2025-01-27 15:38 UTC, dmannarino commented on app/routes/thematic/geoencoder.py
> +    if re.match(VERSION_REGEX, version) is None:
Now specified on a per-env basis!

2025-01-27 19:02 UTC, gtempus requested changes
I like the new name of the endpoint, Daniel!

What about changing the name of the model from geoencoder? 😬

2025-01-27 19:02 UTC, gtempus commented on app/routes/political/id_lookup.py
> +def sanitize_names(
What about `normalilze_names`? Sanitize comes with a different connotation about what this method does.

2025-01-27 19:41 UTC, dmannarino commented on app/routes/political/id_lookup.py
> +def sanitize_names(
Roger, will change, thanks!

2025-01-27 19:42 UTC, dmannarino commented
> I like the new name of the endpoint, Daniel!
> 
> What about changing the name of the model from geoencoder? 😬

Yes, that's the right thing to do. :) Will do, thanks!

2025-01-28 01:20 UTC, danscales reviewed
Looks good to me!

2025-01-28 01:20 UTC, danscales commented on app/routes/political/id_lookup.py
> +    }
Nit (optional): I guess this code works in Pydantic, but the types would be clearer if 'data' was a AdminIDLookupResponseData, which I guess you could do via:

data = AdminIDLookupResponseData(**{
  "adminSource": admin_source,
        "adminVersion": admin_version,
        "matches": matches,
  })

2025-01-28 23:15 UTC, danscales approved these changes

2025-01-29 01:33 UTC, merged